### PR TITLE
Added Trust region to LSQR

### PR DESCRIPTION
**Pull request by syarra**
I added a trust-region constraint to LSQR.
This file is now a merge of `NLPy`'s LSQR and `pykrylov` LSQR

**Warning**: trust region is now in 2 norm!

### CODE REVIEW

**Comment by dpo** [comment]
This can be tricky. Could you add tests where the solution is
1. inside
2. on the boundary
3. outside.
The exact solution should be known so we can compare.

**Comment by dpo** [comment]
Could you just add a word of warning in the docstring that the trust-region constraint only applies in the 2-norm?

**Comment by syarra** [comment]
Done!

**Comment by dpo** [comment]
Great! Thanks!

**Pull request merged**
